#!/bin/bash
# Проверяем, передан ли аргумент (имя каталога)
if [ $# -ne 1 ]; then
    echo "Usage: $0 directory"
    exit 1
fi
# Проверяем, существует ли указанный каталог
if [ ! -d "$1" ]; then
    echo "Directory '$1' does not exist."
    exit 1
fi
# Выводим содержимое каталога
echo "Contents of directory '$1':"
ls "$1"